FROM golang:1.26.6-alpine

RUN apk add --no-cache git ca-certificates build-base && \
    go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080 8081

CMD ["air", "-c", ".air.toml"]
