#!/usr/bin/env bash
# AegisFlow PR-Writer Installer
# A focused, idempotent installer for the PR-writer demo workflow.
set -u

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

START_TS=$(date +%s)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$PROJECT_ROOT/.aegisflow-run"
mkdir -p "$LOG_DIR"

pass() { echo -e "  ${GREEN}PASS${NC} $1"; }
fail() { echo -e "  ${RED}FAIL${NC} $1"; }
info() { echo -e "  $1"; }
hdr()  { echo ""; echo -e "${BOLD}$1${NC}"; }

cleanup_fail() {
    echo ""
    echo -e "${RED}${BOLD}Installation failed.${NC}"
    echo "  Logs: $LOG_DIR"
    exit 1
}

# ---------------------------------------------------------------------------
hdr "AegisFlow PR-Writer Installer"
echo "==========================================="

# ---- 1. Prerequisites ----
hdr "1) Checking prerequisites"

if ! command -v go >/dev/null 2>&1; then
    fail "Go not found (need 1.26.6+)"
    cleanup_fail
fi
GO_VER=$(go version | awk '{print $3}' | sed 's/go//')
GO_MAJOR=$(echo "$GO_VER" | cut -d. -f1)
GO_MINOR=$(echo "$GO_VER" | cut -d. -f2)
GO_PATCH=$(echo "$GO_VER" | cut -d. -f3)
GO_PATCH="${GO_PATCH:-0}"
if [ "$GO_MAJOR" -lt 1 ] || \
   { [ "$GO_MAJOR" -eq 1 ] && [ "$GO_MINOR" -lt 26 ]; } || \
   { [ "$GO_MAJOR" -eq 1 ] && [ "$GO_MINOR" -eq 26 ] && [ "$GO_PATCH" -lt 6 ]; }; then
    fail "Go $GO_VER too old (need 1.26.6+)"
    cleanup_fail
fi
pass "Go $GO_VER"

if ! command -v node >/dev/null 2>&1; then
    fail "node not found (needed for mock MCP server)"
    cleanup_fail
fi
pass "node $(node --version)"

if ! command -v jq >/dev/null 2>&1; then
    fail "jq not found"
    cleanup_fail
fi
pass "jq $(jq --version)"

if ! command -v curl >/dev/null 2>&1; then
    fail "curl not found"
    cleanup_fail
fi
pass "curl"

# ---- 2. Free required ports ----
hdr "2) Freeing ports 8080, 8081, 8082, 3000"

free_port() {
    local port=$1
    local pids
    pids=$(lsof -ti tcp:"$port" 2>/dev/null || true)
    if [ -n "$pids" ]; then
        echo "$pids" | xargs kill -9 2>/dev/null || true
        info "killed pids on :$port -> $pids"
    fi
}
free_port 8080
free_port 8081
free_port 8082
free_port 3000
pass "ports clear"

# ---- 3. Generate config ----
hdr "3) Generating configs/pr-writer.yaml"

CONFIG_DIR="$PROJECT_ROOT/configs"
mkdir -p "$CONFIG_DIR"
POLICY_FILE="$SCRIPT_DIR/policies/pr-writer.yaml"
if [ ! -f "$POLICY_FILE" ]; then
    fail "missing $POLICY_FILE"
    cleanup_fail
fi

POLICY_BLOCK=$(awk '/^tool_policies:/{flag=1} flag' "$POLICY_FILE")

cat > "$CONFIG_DIR/pr-writer.yaml" <<YAML
# Auto-generated by starter-kit/install-pr-writer.sh
# Tuned for the PR-writer demo workflow.
server:
  port: 8080
  admin_port: 8081

providers:
  - name: "mock"
    type: "mock"
    enabled: true
    default: true

tenants:
  - id: "pr-writer-agent"
    name: "PR Writer Demo Agent"
    api_keys:
      - key: "pr-writer-key-001"
        role: "admin"
    rate_limit:
      requests_per_minute: 240
      tokens_per_minute: 400000

routes:
  - match:
      model: "*"
    providers: ["mock"]
    strategy: "priority"

state:
  enabled: true
  sqlite_path: ".aegisflow-run/state.db"

${POLICY_BLOCK}

policies:
  governance_mode: "governance"
  input:
    - name: "block-jailbreak"
      type: "keyword"
      action: "block"
      keywords:
        - "ignore previous instructions"

shell_gate:
  enabled: true
  block_dangerous: true

sql_gate:
  enabled: true
  block_dangerous: true

mcp_gateway:
  enabled: true
  port: 8082
  upstreams:
    - name: "github-mock"
      url: "http://localhost:3000"
      tools: ["github.*"]
YAML
pass "wrote configs/pr-writer.yaml"

EVIDENCE_KEY_FILE="$LOG_DIR/evidence.key"
if [ ! -s "$EVIDENCE_KEY_FILE" ]; then
    if ! (umask 077; od -An -N32 -tx1 /dev/urandom | tr -d '[:space:]' > "$EVIDENCE_KEY_FILE"); then
        fail "could not generate evidence signing key"
        cleanup_fail
    fi
fi
chmod 600 "$EVIDENCE_KEY_FILE"
EVIDENCE_KEY=$(tr -d '[:space:]' < "$EVIDENCE_KEY_FILE")
if [ "${#EVIDENCE_KEY}" -ne 64 ]; then
    fail "invalid evidence signing key"
    cleanup_fail
fi
pass "persistent approval and evidence state"

# ---- 4. Build ----
hdr "4) Building aegisflow + aegisctl"

cd "$PROJECT_ROOT"
if ! go build -o bin/aegisflow ./cmd/aegisflow >"$LOG_DIR/build.log" 2>&1; then
    fail "go build aegisflow"
    tail -20 "$LOG_DIR/build.log"
    cleanup_fail
fi
pass "bin/aegisflow"

if ! go build -o bin/aegisctl ./cmd/aegisctl >>"$LOG_DIR/build.log" 2>&1; then
    fail "go build aegisctl"
    tail -20 "$LOG_DIR/build.log"
    cleanup_fail
fi
pass "bin/aegisctl"

# ---- 5. Start AegisFlow ----
hdr "5) Starting AegisFlow"

nohup env AEGISFLOW_EVIDENCE_KEY="$EVIDENCE_KEY" \
    bin/aegisflow --config configs/pr-writer.yaml \
    >"$LOG_DIR/aegisflow.log" 2>&1 &
AEGIS_PID=$!
echo "$AEGIS_PID" > "$LOG_DIR/aegisflow.pid"
info "pid $AEGIS_PID -> $LOG_DIR/aegisflow.log"

ready=false
for i in $(seq 1 30); do
    if curl -sf http://localhost:8080/health >/dev/null 2>&1; then
        ready=true
        break
    fi
    sleep 1
done
if [ "$ready" != true ]; then
    fail "aegisflow did not become healthy"
    tail -30 "$LOG_DIR/aegisflow.log"
    cleanup_fail
fi
pass "aegisflow healthy on :8080"

# ---- 6. Start mock MCP server ----
hdr "6) Starting mock MCP server"

nohup node "$PROJECT_ROOT/scripts/mock-mcp-server.js" \
    >"$LOG_DIR/mock-mcp.log" 2>&1 &
MOCK_PID=$!
echo "$MOCK_PID" > "$LOG_DIR/mock-mcp.pid"
info "pid $MOCK_PID -> $LOG_DIR/mock-mcp.log"

ready=false
for i in $(seq 1 15); do
    if curl -sf http://localhost:3000/ >/dev/null 2>&1 || \
       curl -s http://localhost:3000/ >/dev/null 2>&1; then
        ready=true
        break
    fi
    sleep 1
done
if [ "$ready" != true ]; then
    fail "mock MCP server did not start"
    tail -20 "$LOG_DIR/mock-mcp.log"
    cleanup_fail
fi
pass "mock MCP server on :3000"

# ---- 7. Write .mcp.json ----
hdr "7) Writing .mcp.json"

BRIDGE_PATH="$PROJECT_ROOT/scripts/mcp-stdio-bridge.sh"
chmod +x "$BRIDGE_PATH" 2>/dev/null || true
cat > "$PROJECT_ROOT/.mcp.json" <<JSON
{
  "mcpServers": {
    "aegisflow": {
      "command": "bash",
      "args": ["$BRIDGE_PATH"],
      "env": {
        "AEGISFLOW_MCP_URL": "http://localhost:8082/mcp"
      }
    }
  }
}
JSON
pass ".mcp.json -> aegisflow stdio bridge"

# ---- 8. Sanity checks ----
hdr "8) Running sanity checks"

CHECKS_FAILED=0

# (a) Health
if curl -sf http://localhost:8080/health >/dev/null 2>&1 && \
   curl -sf http://localhost:8081/health >/dev/null 2>&1; then
    pass "(a) health endpoints healthy"
else
    fail "(a) health endpoints"
    CHECKS_FAILED=$((CHECKS_FAILED+1))
fi

# (b) Safe action allowed
ALLOW_JSON=$(curl -s -X POST http://localhost:8081/admin/v1/test-action \
    -H "Content-Type: application/json" \
    -H "X-API-Key: pr-writer-key-001" \
    -d '{"protocol":"mcp","tool":"github.list_repos","target":"myorg","capability":"read"}')
ALLOW_DECISION=$(echo "$ALLOW_JSON" | jq -r '.decision // "unknown"')
if [ "$ALLOW_DECISION" = "allow" ]; then
    pass "(b) github.list_repos -> allow"
else
    fail "(b) github.list_repos -> $ALLOW_DECISION (expected allow)"
    echo "    raw: $ALLOW_JSON"
    CHECKS_FAILED=$((CHECKS_FAILED+1))
fi

# (c) Risky write queued for review
REVIEW_JSON=$(curl -s -X POST http://localhost:8081/admin/v1/test-action \
    -H "Content-Type: application/json" \
    -H "X-API-Key: pr-writer-key-001" \
    -d '{"protocol":"mcp","tool":"github.create_pull_request","target":"myorg/myrepo","capability":"write"}')
REVIEW_DECISION=$(echo "$REVIEW_JSON" | jq -r '.decision // "unknown"')
if [ "$REVIEW_DECISION" = "review" ]; then
    pass "(c) github.create_pull_request -> review"
else
    fail "(c) github.create_pull_request -> $REVIEW_DECISION (expected review)"
    echo "    raw: $REVIEW_JSON"
    CHECKS_FAILED=$((CHECKS_FAILED+1))
fi

# (d) Dangerous action blocked
BLOCK_JSON=$(curl -s -X POST http://localhost:8081/admin/v1/test-action \
    -H "Content-Type: application/json" \
    -H "X-API-Key: pr-writer-key-001" \
    -d '{"protocol":"mcp","tool":"github.delete_repo","target":"myorg/myrepo","capability":"delete"}')
BLOCK_DECISION=$(echo "$BLOCK_JSON" | jq -r '.decision // "unknown"')
if [ "$BLOCK_DECISION" = "block" ]; then
    pass "(d) github.delete_repo -> block"
else
    fail "(d) github.delete_repo -> $BLOCK_DECISION (expected block)"
    echo "    raw: $BLOCK_JSON"
    CHECKS_FAILED=$((CHECKS_FAILED+1))
fi

if [ "$CHECKS_FAILED" -gt 0 ]; then
    echo ""
    echo -e "${RED}${BOLD}$CHECKS_FAILED sanity check(s) failed.${NC}"
    echo "  Run starter-kit/uninstall-pr-writer.sh to clean up."
    exit 1
fi

# ---- Done ----
END_TS=$(date +%s)
ELAPSED=$((END_TS - START_TS))
MIN=$((ELAPSED / 60))
SEC=$((ELAPSED % 60))

echo ""
echo -e "${GREEN}${BOLD}===========================================${NC}"
echo -e "${GREEN}${BOLD}AegisFlow PR-Writer is ready.${NC}"
echo -e "${GREEN}${BOLD}===========================================${NC}"
echo ""
echo "  Policy:    pr-writer"
echo "  Gateway:   http://localhost:8080"
echo "  Admin:     http://localhost:8081"
echo "  MCP:       http://localhost:8082"
echo "  Mock MCP:  http://localhost:3000"
echo ""
echo -e "  Installed and verified in ${BOLD}${MIN}m ${SEC}s${NC}"
echo ""
echo -e "${BOLD}Done. Now open Claude Code in this directory and type:${NC}"
echo -e "  ${GREEN}'list my github repos using aegisflow tools'${NC}"
echo ""
echo "To shut down:  ./starter-kit/uninstall-pr-writer.sh"
echo ""
exit 0
